### PR TITLE
Added in tamil language

### PR DESCRIPTION
**Pull request by saratkumar17mss040**
added in tamil language for the code of conduct!

### CODE REVIEW

**Comment by Pushkraj19** [comment]
Nice now create one in Hindi also.

**Comment by w3cj** [comment]
Thank you for this! I'd like you to make some updates:

* At the very beginning, TLDR got translated to DLDR. TLDR is an acronym for "Too Long Didn't Read", not sure if there is a similar acronym in tamil.
* The channel names (e.g. #introductions) should remain in English (see other translation files for an example.)
* I ran the translation through google translate, and there are a few things that might have better translations:
  * Moderator got translated to Evaluator. Not sure if there is a better translation, but a moderator is someone who is like an administrator for the server, they make sure everyone is adhering to the code of conduct, keep everyone in line and they help people if needed.
  * In section 1 of the code of conduct, `neuro-type` was translated to `neurotic type` (this is incorrect)
    * I'm not sure if there is a direct translation for `neuro-type` in tamil. The simplest way to say this in English might be `brain type` and typically deals with how a person interprets and responds to social cues. Some related terms are `neurotypical` and `neurodivergent`
  * Near the end of the translation, `pruner` got translated to `bruner`. The term `pruner` comes from gardening, to prune - to cut off or remove dead or living parts or branches of (a plant, for example) to improve shape or growth. The term pruner is used as a metaphor for moderator, because the moderators help tend to the coding garden.

**Comment by saratkumar17mss040** [comment]
ok w3cj after changing all these things do i need to make another pull requests or will the change be reflected in this pull requests itself . before doing any pull request do i need to pull the changes that are made in your repo as i am somewhat new to git and github sorry for asking these questions but i am trying to contribute of what i could do now

**Comment by saratkumar17mss040** [comment]
I changed to the english version - TLDR, to the english version all the different channels in the server - eg : #introductions,moderator to நடுவர் as it is the correct one for it,then for pruner  i changed it to the close term -(pruners- தோட்டக்காரர்கள்) , (pruner-தோட்டக்காரர்),and neuro-type i changed to the pronounciation version of english to tamil as there seems to be not a close term for it. Hope you like it.

**Comment by w3cj** [comment]
Thank you! 💚

**Pull request merged**
